# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .contact import Contact
from .domain_registrar import DomainRegistrar
from .historical_record import HistoricalRecord
from .registry_data import RegistryData
from .reseller_contact import ResellerContact
from .status import Status


class WhoisResponse(UniversalBaseModel):
    status: typing.Optional[Status] = None
    domain_name: typing.Optional[str] = None
    query_time: typing.Optional[str] = None
    whois_server: typing.Optional[str] = None
    domain_registered: typing.Optional[str] = None
    create_date: typing.Optional[str] = None
    update_date: typing.Optional[str] = None
    expiry_date: typing.Optional[str] = None
    domain_registrar: typing.Optional[DomainRegistrar] = None
    reseller_contact: typing.Optional[ResellerContact] = None
    registrant_contact: typing.Optional[Contact] = None
    administrative_contact: typing.Optional[Contact] = None
    technical_contact: typing.Optional[Contact] = None
    billing_contact: typing.Optional[Contact] = None
    name_servers: typing.Optional[typing.List[str]] = None
    domain_status: typing.Optional[typing.List[str]] = None
    whois_raw_domain: typing.Optional[str] = None
    registry_data: typing.Optional[RegistryData] = None
    raw_response: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="rawResponse")] = None
    whois: typing.Optional[str] = None
    total_records: typing.Optional[str] = None
    total_result: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="total_Result")] = None
    total_pages: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="total_Pages")] = None
    current_page: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="current_Page")] = None
    whois_domains_historical: typing.Optional[typing.List[HistoricalRecord]] = None
    timestamp: typing.Optional[str] = None
    error: typing.Optional[str] = None
    message: typing.Optional[str] = None
    path: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
