# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from .dns_live_response import DnsLiveResponse
from .dns_record import DnsRecord

__all__ = ["DnsLiveResponse", "DnsRecord"]
