# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .historical_dns_record import HistoricalDnsRecord


class DnsReverseResponse(UniversalBaseModel):
    total_records: typing.Optional[int] = None
    total_pages: typing.Optional[int] = None
    current_page: typing.Optional[int] = None
    reverse_dns_records: typing.Optional[typing.List[HistoricalDnsRecord]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
