# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .ssl_certificate import SslCertificate


class SslLiveLookupResponse(UniversalBaseModel):
    domain_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="domainName")] = None
    query_time: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="queryTime")] = None
    ssl_certificates: typing_extensions.Annotated[
        typing.Optional[typing.List[SslCertificate]], FieldMetadata(alias="sslCertificates")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
